name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-key-alias -storepass TufailUzma123 -keypass TufailUzma123 -dname "CN=Meri Wife, OU=Personal, O=MyApp, L=Karachi, S=Sindh, C=PK"

      - name: Convert to Base64
        run: base64 my-release-key.jks > keystore-base64.txt

      - name: Upload Keystore Files
        uses: actions/upload-artifact@v4
        with:
          name: keystore-files
          path: |
            my-release-key.jks
            keystore-base64.txt